MvcStok/MvcStok/Controllers/KategoriController.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            //var kategoriler = db.TblKategoriler.ToList();
            var kategoriler = db.TblKategoriler.ToList().ToPagedList(sayfa,5);

            return View(kategoriler);
        }


        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKategori(TblKategoriler p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }   
            db.TblKategoriler.Add(p1);
            db.SaveChanges();
            return View();
        }



        public ActionResult Sil(int id)
        {
            var ktg = db.TblKategoriler.Find(id);
            db.TblKategoriler.Remove(ktg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TblKategoriler.Find(id);
            return View("KategoriGetir",ktgr);
        }

        public ActionResult Guncelle(TblKategoriler p1)
        {
            var ktg = db.TblKategoriler.Find(p1.KategoriID);
            ktg.KategoriAd = p1.KategoriAd;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@model PagedList.IPagedList<TblKategoriler>
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Kategori ID</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @item.KategoriID
                </th>
                <td>
                    @item.KategoriAd
                </td>
                <td><a href="/Kategori/Sil/@item.KategoriID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Kategori/KategoriGetir/@item.KategoriID" class="btn btn-primary">Güncelle</a></td>
            </tr>
        }

    </tbody>
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/Kategori/YeniKategori/" class="btn btn-success">Yeni Kategori Ekle</a>

MvcStok/MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.Entity.TblKategoriler
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<!--Guncelle çalışacak,Kategori controller içinde,post edildiği zaman çalışacak -->
@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.KategoriID)
        @Html.TextBoxFor(m => m.KategoriID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.KategoriAd)
        @Html.TextBoxFor(m => m.KategoriAd, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">
            Kategori Güncelle
        </button>
    </div>
}

MvcStok/MvcStok/Views/Kategori/YeniKategori.cshtml
@model MvcStok.Models.Entity.TblKategoriler
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<form class="form-group" method="post">
    @*<div>
        <label>Kategori Adı</label>
            <input type="text" class="form-control" name="KategoriAd" />
        </div>*@
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=>m.KategoriAd,new{@class="form-control" })
        @Html.ValidationMessageFor(m=>m.KategoriAd,"",new {@style="color:red"})
    </div>


    <div style="margin-top:15px">
        <button class="btn btn-info"> Kategori Ekle</button>
    </div>
</form>