MvcStok/MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult Index(string p)
        {
            var degerler = from i in db.TblMusteriler select i;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MusteriAd.Contains(p)|| m.MusteriSoyad.Contains(p));
            }
            return View(degerler.ToList());
            
            
            //var musteriler = db.TblMusteriler.ToList();
            //return View(musteriler);

        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TblMusteriler m1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TblMusteriler.Add(m1);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var musteri = db.TblMusteriler.Find(id);
            db.TblMusteriler.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.TblMusteriler.Find(id);
            return View("MusteriGetir",musteri);
        }

        public ActionResult Guncelle(TblMusteriler p1)
        {
            var musteri = db.TblMusteriler.Find(p1.MusteriID);

            musteri.MusteriAd = p1.MusteriAd;
            musteri.MusteriSoyad = p1.MusteriSoyad;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

MvcStok/MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<TblMusteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteri", FormMethod.Get, new { @class = "form-control" }))
{
    <p>
        <b>Aranacak müşteri adı yada soyadı : </b>@Html.TextBox("p")
        <input type="submit" value="Ara" style="background-color:lightseagreen; color:red; border-radius:10px;" />
    </p>
}


<table class="table table-bordered" style="margin-top:10px">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @item.MusteriID
                </th>
                <td>
                    @item.MusteriAd
                </td>
                <td>
                    @item.MusteriSoyad
                </td>

                <td><a href="/Musteri/Sil/@item.MusteriID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Musteri/MusteriGetir/@item.MusteriID" class="btn btn-primary">Güncelle</a></td>
                @*Alert vererek silme kısmı silme işlemi gerçekleştirilirken alert penceresinde emin misiniz diye soruyor*@

                <td>@Html.ActionLink("Sil Butonu", "Sil", new { id = item.MusteriID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor musunuz?')" })</td>
            </tr>
        }

    </tbody>
</table>
<a href="/Musteri/YeniMusteri/" class="btn btn-success">Yeni Musteri Ekle</a>

MvcStok/MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TblMusteriler
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}





@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MusteriID)
        @Html.TextBoxFor(m => m.MusteriID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MusteriAd)
        @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MusteriSoyad)
        @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control" })

    </div>
    <div>
        <button class="btn btn-warning">
            Müşteri Güncelle
        </button>
    </div>
}

MvcStok/MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TblMusteriler
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>
        <div>
            <label>Müşteri Adı</label>
            @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.MusteriAd, "", new { @style = "color:red" })
        </div>

        <div>
            <label style="margin-top:10px">Müşteri Soyadı</label>
            <input type="text" class="form-control" name="MusteriSoyad" />
        </div>


    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1"> Müşteri Ekle</button>
    </div>


    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı...');
        });
    </script>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
</form>