MvcStok/MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index()
        {
            var urunler = db.TblUrunler.ToList();

            return View(urunler);
        }
        [HttpGet]
        public ActionResult YeniUrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TblKategoriler.ToList()
                                             select new SelectListItem()
                                             {
                                                 Text=i.KategoriAd,
                                                 Value=i.KategoriID.ToString()

                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrunEkle(TblUrunler u1)
        {
            var ktg = db.TblKategoriler.Where(m => m.KategoriID == u1.TblKategoriler.KategoriID).FirstOrDefault();
            u1.TblKategoriler = ktg;

            db.TblUrunler.Add(u1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var urun = db.TblUrunler.Find(id);
            db.TblUrunler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> degerler = (from i in db.TblKategoriler.ToList()
                                             select new SelectListItem()
                                             {
                                                 Text = i.KategoriAd,
                                                 Value = i.KategoriID.ToString()

                                             }).ToList();
            ViewBag.dgr = degerler;
            var urun = db.TblUrunler.Find(id);
            db.SaveChanges();
            return View("UrunGetir",urun);
        }

        public ActionResult Guncelle(TblUrunler p1)
        {
            var urun = db.TblUrunler.Find(p1.UrunID);
            urun.UrunAdi = p1.UrunAdi;
            urun.Marka = p1.Marka;
            urun.Stok = p1.Stok;
            urun.Fiyat = p1.Fiyat;
            urun.UrunKategori = p1.UrunKategori;

            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

MvcStok/MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity
@model List<TblUrunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>Urun ID</th>
            <th>Urun Adı</th>
            <th>Marka</th>
            <th>Urun Kategori</th>
            <th>Fiyat</th>
            <th>Stok</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in   Model)
        {
            <tr>
                <th>
                    @item.UrunID
                </th>
                <td>
                    @item.UrunAdi
                </td>
                <td>
                    @item.Marka
                </td>
                <td>
                    @item.TblKategoriler.KategoriAd
                </td>
                <td>
                    @item.Fiyat
                </td>
                <td>
                    @item.Stok
                </td>
                <td><a href="/Urun/Sil/@item.UrunID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Urun/UrunGetir/@item.UrunID" class="btn btn-primary">Güncelle</a></td>


            </tr>
        }

    </tbody>
</table>


<a href="/Urun/YeniUrunEkle/" class="btn btn-success">Yeni Urun Ekle</a>


<script type="text/javascript" src="cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

<script>
    $('#tbl1').DataTable();
</script>

MvcStok/MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TblUrunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.UrunID)
        @Html.TextBoxFor(m => m.UrunID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.UrunAdi)
        @Html.TextBoxFor(m => m.UrunAdi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.Marka)
        @Html.TextBoxFor(m => m.Marka, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.UrunKategori)
        @Html.DropDownListFor(m=>m.UrunKategori,(List<SelectListItem>)ViewBag.dgr ,new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.Fiyat)
        @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.Stok)
        @Html.TextBoxFor(m => m.Stok, new { @class = "form-control" })



    </div>
    <div>
        <button class="btn btn-warning">
            Ürün Güncelle
        </button>
    </div>
}

MvcStok/MvcStok/Views/Urun/YeniUrunEkle.cshtml
@model MvcStok.Models.Entity.TblUrunler 
@{
    ViewBag.Title = "YeniUrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<form class="form-group" method="post">

    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="UrunAdi" required=""/>
    </div>

    <div>
        <label>Ürün Markası</label>
        <input type="text" class="form-control" name="Marka" required=""/>
    </div>

    <div>
        <label>Kategori</label>
        @Html.DropDownListFor(m =>m.TblKategoriler.KategoriID, 
                    (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })

        <!--linq sorgusu ile kategori id sini alıyoruz controller
            tarafından aldığımız viewbag ile de kategori isimlerini yazdırıyoruz-->
    </div>

    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="Fiyat" required maxlength="6"/>
    </div>
    <div>
        <label>Stok</label>
        <input type="text" class="form-control" name="Stok" placeholder="Stok girin"/>
    </div>



    <div style="margin-top:15px">
        <button class="btn btn-info"> Ürün Ekle</button>
    </div>
</form>